dist: xenial
os: linux
branches:
  only:
    - master
cache:
  - bundler
language: ruby
rvm:
  - 2.7.2
  - 2.6.5
  - 2.5.1
addons:
  postgresql: "9.4"
services:
  - postgresql
  - redis
before_script:
  - psql -c 'create database que_test;' -U postgres
gemfile:
  - gemfiles/que_0.12.2.gemfile
  - gemfiles/que_0.12.3.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/shoryuken_4.0.gemfile
  - gemfiles/sidekiq_4.2.gemfile
  - gemfiles/sinatra_1.4.gemfile
  - gemfiles/sinatra_2.0.gemfile
jobs:
  fast_finish: true
